### ISSUE TITLE
Detailed configuration

### ISSUE THREAD

**Issue by ws1922667298** [hippiefm/tms570ls3137-clion-led-blinky#1]
hi
I am a novice. Can you provide a detailed configuration tutorial? Thank you very much.

**Comment by hippiefm** [comment]
Sure, just let me know where you have troubles.

**Comment by ws1922667298** [comment]
thank!
Are you using Mac? When I configured DSlite on Mac m1, it couldn't run. The prompt is as follows
`Debugger executable not found: /Users/xx/work/workspace/CLion/tms570ls3137-clion-led-blinky/flasher/ccs_base/DebugServer/bin/DSLite`
It's really difficult, but eclipse is really too difficult to use

**Comment by hippiefm** [comment]
Yes, I am using Mac with M1. I'll try to set up the project with my manual and I'll let you know.

**Comment by ws1922667298** [comment]
thanks!

**Comment by ws1922667298** [comment]
There was a problem with the previous configuration, but after I reconfigured it, there were new issues
`error: CortexR4: Error connecting to the target: ERROR in JLINKARM_Open: Cannot connect to J-Link.`

**Comment by ws1922667298** [comment]
I have solved some problems again, and now I can use the clion to burn the program onto the board, but I still cannot perform breakpoint debugging.

**Comment by ws1922667298** [comment]
hi,
I don't have jlink so I change jlink.cfg to xds100v2.cfg, now I can use breakpoint debugging,but Sometimes the connection fails.
But it has reached the point where it can be used.
thank for your project and help.

**Comment by hippiefm** [comment]
Good to know it works. I also had troubles with XDS, this is why I changed to JLink. If you have any additional problems, do not hesitate to ask.
